name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Get version
      id: get_version
      run: echo "::set-output name=version::$(python get_version.py)"

    - name: Print directory contents for debugging
      run: ls -R

    - name: Update README
      run: |
        version=$(echo ${{ steps.get_version.outputs.version }})
        echo "Version: $version"
        cp assets/README_template.md README.md
        sed -i "s/{{ version }}/$version/g" README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update README with version ${{ steps.get_version.outputs.version }}"
        git push https://github.com/${{ github.repository }}.git HEAD:main
        git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

